version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:management"
    hostname: "rabbit"
    restart: always
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: cshop
      RABBITMQ_DEFAULT_PASS: cshop
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

